#pragma once

typedef enum {
    COMMON_ERROR_CODE_OK,
    COMMON_ERROR_CODE_MEMORY_ALLOCATION_FAILURE,
    COMMON_ERROR_CODE_OVERFLOW,
    COMMON_ERROR_CODE_NOT_FOUND,
    COMMON_ERROR_CODE_FILE_ERROR,
    COMMON_ERROR_CODE_UNEXPECTED_CHARACTER,
    COMMON_ERROR_CODE_UNEXPECTED_EOF,
    COMMON_ERROR_CODE_NUMBER_TOO_LARGE,
    COMMON_ERROR_CODE_MALFORMED_NUMBER,
} common_error_code_t;
