#pragma once

#include "common/util/concat-token.h"

#define COLLECTION_DECLARE 0x1
#define COLLECTION_DEFINE 0x2
#define COLLECTION_EXPORT_GENERIC_NAME 0x4
#define COLLECTION_STATIC 0x8

#define COLLECTION_DEFAULT (COLLECTION_DECLARE | COLLECTION_DEFINE)
